services:
  postgres:
    image: postgres:15-alpine
    container_name: quiz_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-quiz_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-ur_psswrd}
      POSTGRES_DB: ${DB_NAME:-quiz_eclair}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
